# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('search_url', models.URLField()),
                ('word_search', models.CharField(max_length=100)),
            ],
        ),
    ]
